server:
  port: 80

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/corn
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: corn
    password: Corn2020!@#

  cache:
    type: redis
    redis:
      key-prefix: sms_
#      time-to-live: 10s
      use-key-prefix: true
#      cache-null-values: false
  redis:
    host: localhost
    port: 6379
    password: 'qwe!@#'

#  ehcache配置
#  cache:
#    type: ehcache
#    ehcache:
#      config: ehcache.xml


mybatis-plus:
  global-config:
    db-config:
      table-prefix: eng_
      id-type: auto
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

