server:
  port: 80
logging:
  group:
    abc: com.seed.controller,com.seed.service
  level:
    root: info
    abc: debug
  pattern:
    console: "%d %clr(%5p)  --- [%16t] %clr(%-40.40c){cyan} : %m %n"
  file:
    name: server.log
  logback:
    rollingpolicy:
      file-name-pattern: server.%d{yyyy-MM-dd}.%i.log
      max-file-size: 4KB

