spring:
  profiles:
    active: test
---
# 应用环境
# 过时写法
spring:
  profiles: pro
server:
  port: 80
---
# 设置环境
spring:
  profiles: dev
server:
  port: 81
---
# 生产环境
server:
  port: 82
# 不过时写法
spring:
  config:
    activate:
      on-profile: test
