spring:
  datasource:
      url: jdbc:mysql://42.192.15.59:3306/corn?characterEncoding=UTF-8&useUnicode=true&useSSL=false&serverTimezone=UTC
      username: corn
      password: corn2020!@#
      driver-class-name: com.mysql.cj.jdbc.Driver

# DataSource Config
#spring:
#  datasource:
#    driver-class-name: org.h2.Driver
#    username: root
#    password: test
